package com.civil.converter;
// Generated Jan 20, 2020 10:27:03 PM by Hibernate Tools 4.3.1

import com.civil.detail.*;
import com.civil.model.*;

/**
 * ProjectsItem generated by hbm2java
 */
public class ProjectsItemConverter {

    public static ProjectsItem getEntity(ProjectsItemDetail detail) {

        if (detail == null) {
            return null;
        }
        ProjectsItem entity = new ProjectsItem();
        entity.setId(detail.getId());
        entity.setProject(ProjectConverter.getEntity(detail.getProjectDetail()));
        entity.setItem(ItemConverter.getEntity(detail.getItemDetail()));
        entity.setQuantity(detail.getQuantity());
        entity.setTotalPrice(detail.getTotalPrice());
        entity.setCalculationSummary(detail.getCalculationSummary() == null ? "" : detail.getCalculationSummary());
        return entity;
    }

    public static ProjectsItemDetail getDetail(ProjectsItem entity) {
        if (entity == null) {
            return null;
        }
        ProjectsItemDetail detail = new ProjectsItemDetail();
        detail.setId(entity.getId());
        detail.setProjectDetail(ProjectConverter.getDetail(entity.getProject()));
        detail.setItemDetail(ItemConverter.getDetail(entity.getItem()));
        detail.setQuantity(entity.getQuantity() == null ? 0 : entity.getQuantity());
        detail.setTotalPrice(entity.getTotalPrice() == null ? 0 : entity.getTotalPrice());
        
        detail.setCalculationSummary(entity.getCalculationSummary() == null ? "" : entity.getCalculationSummary());
        
      
        return detail;
    }

}
