package com.civil.converter;
// Generated Jan 20, 2020 10:27:03 PM by Hibernate Tools 4.3.1

import com.civil.detail.ProjectDetail;
import com.civil.model.Project;

/**
 * Project generated by hbm2java
 */
public class ProjectConverter {

    public static Project getEntity(ProjectDetail detail) {
        if (detail == null) {
            return null;
        }
        Project entity = new Project();

        entity.setId(detail.getId());
        entity.setProjectName(detail.getProjectName());
        entity.setStartDate(detail.getStartDate());
        entity.setEndDate(detail.getEndDate());
        entity.setMinistry(detail.getMinistry());
        return entity;
    }

    public static ProjectDetail getDetail(Project entity) {
        if (entity == null) {
            return null;
        }
        ProjectDetail detail = new ProjectDetail();
        detail.setId(entity.getId());
        detail.setProjectName(entity.getProjectName());
        detail.setStartDate(entity.getStartDate());
        detail.setEndDate(entity.getEndDate());
        detail.setMinistry(entity.getMinistry() == null ? "" : entity.getMinistry());
        return detail;
    }

}
