package com.civil.model;
// Generated Dec 17, 2019 12:04:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="civil"
)
public class Employee  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String fatherName;
     private String motherName;
     private String mobileNumber;
     private String nid;
     private String passportNumber;
     private String drivingLicense;
     private String imageUrl;
     private String email;
     private String permanentAddress;
     private String presentAddress;
     private Integer sex;
     private Date dob;
     private String placeOfBirth;
     private String nationality;
     private String degree;
     private String subject;
     private String institution;
     private String year;
     private String religion;
     private String birthCertificate;
     private String bloodGroup;
     private String post;
     private Date joinDate;
     private Date leaveDate;
     private Integer active;
     private String officeId;
     private String salaryGrade;
     private Date createdate;
     private Set<User> users = new HashSet<User>(0);

    public Employee() {
    }

    public Employee(String firstName, String lastName, String fatherName, String motherName, String mobileNumber, String nid, String passportNumber, String drivingLicense, String imageUrl, String email, String permanentAddress, String presentAddress, Integer sex, Date dob, String placeOfBirth, String nationality, String degree, String subject, String institution, String year, String religion, String birthCertificate, String bloodGroup, String post, Date joinDate, Date leaveDate, Integer active, String officeId, String salaryGrade, Date createdate, Set<User> users) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.fatherName = fatherName;
       this.motherName = motherName;
       this.mobileNumber = mobileNumber;
       this.nid = nid;
       this.passportNumber = passportNumber;
       this.drivingLicense = drivingLicense;
       this.imageUrl = imageUrl;
       this.email = email;
       this.permanentAddress = permanentAddress;
       this.presentAddress = presentAddress;
       this.sex = sex;
       this.dob = dob;
       this.placeOfBirth = placeOfBirth;
       this.nationality = nationality;
       this.degree = degree;
       this.subject = subject;
       this.institution = institution;
       this.year = year;
       this.religion = religion;
       this.birthCertificate = birthCertificate;
       this.bloodGroup = bloodGroup;
       this.post = post;
       this.joinDate = joinDate;
       this.leaveDate = leaveDate;
       this.active = active;
       this.officeId = officeId;
       this.salaryGrade = salaryGrade;
       this.createdate = createdate;
       this.users = users;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="first_name", length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="father_name", length=50)
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    
    @Column(name="mother_name", length=50)
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    
    @Column(name="mobile_number", length=50)
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    
    @Column(name="nid", length=50)
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }

    
    @Column(name="passport_number", length=50)
    public String getPassportNumber() {
        return this.passportNumber;
    }
    
    public void setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber;
    }

    
    @Column(name="driving_license", length=50)
    public String getDrivingLicense() {
        return this.drivingLicense;
    }
    
    public void setDrivingLicense(String drivingLicense) {
        this.drivingLicense = drivingLicense;
    }

    
    @Column(name="image_url", length=50)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="email", length=1000)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="permanent_address", length=1000)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }
    
    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    
    @Column(name="present_address", length=1000)
    public String getPresentAddress() {
        return this.presentAddress;
    }
    
    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }

    
    @Column(name="sex")
    public Integer getSex() {
        return this.sex;
    }
    
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dob", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="place_of_birth", length=50)
    public String getPlaceOfBirth() {
        return this.placeOfBirth;
    }
    
    public void setPlaceOfBirth(String placeOfBirth) {
        this.placeOfBirth = placeOfBirth;
    }

    
    @Column(name="nationality", length=50)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="degree", length=400)
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }

    
    @Column(name="subject", length=50)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="institution", length=200)
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }

    
    @Column(name="year", length=50)
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }

    
    @Column(name="religion", length=50)
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }

    
    @Column(name="birth_certificate", length=50)
    public String getBirthCertificate() {
        return this.birthCertificate;
    }
    
    public void setBirthCertificate(String birthCertificate) {
        this.birthCertificate = birthCertificate;
    }

    
    @Column(name="blood_group", length=50)
    public String getBloodGroup() {
        return this.bloodGroup;
    }
    
    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    
    @Column(name="post", length=20)
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="join_date", length=10)
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="leave_date", length=10)
    public Date getLeaveDate() {
        return this.leaveDate;
    }
    
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    
    @Column(name="active")
    public Integer getActive() {
        return this.active;
    }
    
    public void setActive(Integer active) {
        this.active = active;
    }

    
    @Column(name="office_id", length=20)
    public String getOfficeId() {
        return this.officeId;
    }
    
    public void setOfficeId(String officeId) {
        this.officeId = officeId;
    }

    
    @Column(name="salary_grade", length=50)
    public String getSalaryGrade() {
        return this.salaryGrade;
    }
    
    public void setSalaryGrade(String salaryGrade) {
        this.salaryGrade = salaryGrade;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdate", length=10)
    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


