package com.civil.model;
// Generated Jan 6, 2020 2:47:33 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "civil"
)
public class Item implements java.io.Serializable {

    private Integer id;
    private Item item;
    private String code;
    private String description;
    private String unit;
    private Float price;
    private String parentCode;
    private String parentItemDescription;
    private String showCode;
    private Set<Item> items = new HashSet<Item>(0);
    private Set<ProjectsItem> projectsItems = new HashSet<ProjectsItem>(0);

    public Item() {
    }

    public Item(String code) {
        this.code = code;
    }

    public Item(Item item, String code, String description, String unit, Float price, String parentCode, String parentItemDescription, String showCode, Set<Item> items, Set<ProjectsItem> projectsItems) {
        this.item = item;
        this.code = code;
        this.description = description;
        this.unit = unit;
        this.price = price;
        this.parentCode = parentCode;
        this.parentItemDescription = parentItemDescription;
        this.showCode = showCode;
        this.items = items;
        this.projectsItems = projectsItems;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    public Item getItem() {
        return this.item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    @Column(name = "code", nullable = false, length = 50)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "unit", length = 50)
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Column(name = "price", precision = 12, scale = 0)
    public Float getPrice() {
        return this.price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    @Column(name = "parent_code", length = 50)
    public String getParentCode() {
        return this.parentCode;
    }

    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    @Column(name = "parent_item_description")
    public String getParentItemDescription() {
        return this.parentItemDescription;
    }

    public void setParentItemDescription(String parentItemDescription) {
        this.parentItemDescription = parentItemDescription;
    }

    @Column(name = "show_code", length = 1000)
    public String getShowCode() {
        return this.showCode;
    }

    public void setShowCode(String showCode) {
        this.showCode = showCode;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<Item> getItems() {
        return this.items;
    }

    public void setItems(Set<Item> items) {
        this.items = items;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "item")
    public Set<ProjectsItem> getProjectsItems() {
        return this.projectsItems;
    }

    public void setProjectsItems(Set<ProjectsItem> projectsItems) {
        this.projectsItems = projectsItems;
    }

}
