package com.civil.model;
// Generated Dec 17, 2019 12:04:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Page generated by hbm2java
 */
@Entity
@Table(name = "page", catalog = "civil"
)
public class Page implements java.io.Serializable {

    private Integer id;
    private Page page;
    private String url;
    private String name;
    private Integer type;
    private Date createdate;
    private String nameBangla;
    private String cssClass;
    private String headerName;
    private Integer position;
    private Set<Page> pages = new HashSet<Page>(0);
    private Set<RolePage> rolePages = new HashSet<RolePage>(0);

    public Page() {
    }

    public Page(int id) {
        this.id = id;
    }

    public Page(Page page, String url, String name, Integer type, Date createdate, String nameBangla, String cssClass, String headerName, Integer position, Set<Page> pages, Set<RolePage> rolePages) {
        this.page = page;
        this.url = url;
        this.name = name;
        this.type = type;
        this.createdate = createdate;
        this.nameBangla = nameBangla;
        this.cssClass = cssClass;
        this.headerName = headerName;
        this.position = position;
        this.pages = pages;
        this.rolePages = rolePages;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_id")
    public Page getPage() {
        return this.page;
    }

    public void setPage(Page page) {
        this.page = page;
    }

    @Column(name = "url", length = 100)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "type")
    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "createdate", length = 10)
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    @Column(name = "name_bangla", length = 100)
    public String getNameBangla() {
        return this.nameBangla;
    }

    public void setNameBangla(String nameBangla) {
        this.nameBangla = nameBangla;
    }

    @Column(name = "css_class", length = 100)
    public String getCssClass() {
        return this.cssClass;
    }

    public void setCssClass(String cssClass) {
        this.cssClass = cssClass;
    }

    @Column(name = "header_name", length = 100)
    public String getHeaderName() {
        return this.headerName;
    }

    public void setHeaderName(String headerName) {
        this.headerName = headerName;
    }

    @Column(name = "position")
    public Integer getPosition() {
        return this.position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "page")
    public Set<Page> getPages() {
        return this.pages;
    }

    public void setPages(Set<Page> pages) {
        this.pages = pages;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "page")
    public Set<RolePage> getRolePages() {
        return this.rolePages;
    }

    public void setRolePages(Set<RolePage> rolePages) {
        this.rolePages = rolePages;
    }

}
