package com.civil.model;
// Generated Mar 6, 2020 2:04:30 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProjectsItem generated by hbm2java
 */
@Entity
@Table(name = "projects_item", catalog = "civil"
)
public class ProjectsItem implements java.io.Serializable {

    private Integer id;
    private Item item;
    private Project project;
    private Integer quantity;
    private Float totalPrice;
    private Integer calculationType;
    private String calculationSummary;
    private Set<ProjectsItemHistory> peojectsItemDetailHistories = new HashSet<ProjectsItemHistory>(0);

    public ProjectsItem() {
    }

    public ProjectsItem(Item item, Project project, Integer quantity, Float totalPrice,
            Set<ProjectsItemHistory> peojectsItemDetailHistories, int calculationType, String calculationSummary) {
        this.item = item;
        this.project = project;
        this.quantity = quantity;
        this.totalPrice = totalPrice;
        this.calculationType = calculationType;
        this.calculationSummary = calculationSummary;
        this.peojectsItemDetailHistories = peojectsItemDetailHistories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "item_id")
    public Item getItem() {
        return this.item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id")
    public Project getProject() {
        return this.project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    @Column(name = "quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Column(name = "total_price", precision = 12, scale = 0)
    public Float getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    @Column(name = "calculation_type")
    public Integer getCalculationType() {
        return calculationType;
    }

    public void setCalculationType(Integer calculationType) {
        this.calculationType = calculationType;
    }

    @Column(name = "calculation_summary", length = 10000)
    public String getCalculationSummary() {
        return calculationSummary;
    }

    public void setCalculationSummary(String calculationSummary) {
        this.calculationSummary = calculationSummary;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "projectsItem")
    public Set<ProjectsItemHistory> getPeojectsItemDetailHistories() {
        return this.peojectsItemDetailHistories;
    }

    public void setPeojectsItemDetailHistories(Set<ProjectsItemHistory> peojectsItemDetailHistories) {
        this.peojectsItemDetailHistories = peojectsItemDetailHistories;
    }

}
