package com.civil.model;
// Generated Mar 6, 2020 2:04:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectsItemHistory generated by hbm2java
 */
@Entity
@Table(name = "projects_item_history", catalog = "civil"
)
public class ProjectsItemHistory implements java.io.Serializable {

    private Integer id;
    private ProjectsItem projectsItem;
    private String name;
    private Integer int1;
    private Integer int2;
    private Integer int3;
    private String ftIn;
    private String title;
    private Integer isAddition;
    private String groupname;

    public ProjectsItemHistory() {
    }

    public ProjectsItemHistory(ProjectsItem projectsItem, String name, Integer int1, Integer int2, Integer int3, String ftIn, String title, Integer isAddition, String groupname) {
        this.projectsItem = projectsItem;
        this.name = name;
        this.int1 = int1;
        this.int2 = int2;
        this.int3 = int3;
        this.ftIn = ftIn;
        this.title = title;
        this.isAddition = isAddition;
        this.groupname = groupname;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_item_id")
    public ProjectsItem getProjectsItem() {
        return this.projectsItem;
    }

    public void setProjectsItem(ProjectsItem projectsItem) {
        this.projectsItem = projectsItem;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "int1")
    public Integer getInt1() {
        return this.int1;
    }

    public void setInt1(Integer int1) {
        this.int1 = int1;
    }

    @Column(name = "int2")
    public Integer getInt2() {
        return this.int2;
    }

    public void setInt2(Integer int2) {
        this.int2 = int2;
    }

    @Column(name = "int3")
    public Integer getInt3() {
        return this.int3;
    }

    public void setInt3(Integer int3) {
        this.int3 = int3;
    }

    @Column(name = "ft_in", length = 100)
    public String getFtIn() {
        return this.ftIn;
    }

    public void setFtIn(String ftIn) {
        this.ftIn = ftIn;
    }

    @Column(name = "Title", length = 100)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "isAddition")
    public Integer getIsAddition() {
        return this.isAddition;
    }

    public void setIsAddition(Integer isAddition) {
        this.isAddition = isAddition;
    }

    @Column(name = "group_name", length = 100)
    public String getGroup() {
        return this.groupname;
    }

    public void setGroup(String groupname) {
        this.groupname = groupname;
    }

}
