package com.civil.model;
// Generated Dec 17, 2019 12:04:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role",
        catalog = "civil"
)
public class Role implements java.io.Serializable {

    private Integer id;
    private String name;
    private Integer defaultPageId;
    private Integer createBy;
    private Date creationDate;
    private Set<User> users = new HashSet<User>(0);
    private Set<RolePage> rolePages = new HashSet<RolePage>(0);

    public Role() {
    }

    public Role(int id) {
        this.id = id;
    }

    public Role(String name, Integer defaultPageId, Integer createBy, Date creationDate, Set<User> users, Set<RolePage> rolePages) {
        this.name = name;
        this.defaultPageId = defaultPageId;
        this.createBy = createBy;
        this.creationDate = creationDate;
        this.users = users;
        this.rolePages = rolePages;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Name", length = 16)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DefaultPageId")
    public Integer getDefaultPageId() {
        return this.defaultPageId;
    }

    public void setDefaultPageId(Integer defaultPageId) {
        this.defaultPageId = defaultPageId;
    }

    @Column(name = "CreateBy")
    public Integer getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "creationDate", length = 10)
    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
    public Set<RolePage> getRolePages() {
        return this.rolePages;
    }

    public void setRolePages(Set<RolePage> rolePages) {
        this.rolePages = rolePages;
    }

}
