package com.civil.model;
// Generated Oct 19, 2019 10:26:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Settings generated by hbm2java
 */
@Entity
@Table(name="settings"
    ,schema="civil"
)
public class Settings  implements java.io.Serializable {


     private int id;
     private String key;
     private String value;

    public Settings() {
    }

	
    public Settings(int id) {
        this.id = id;
    }
    public Settings(int id, String key, String value) {
       this.id = id;
       this.key = key;
       this.value = value;
    }
   
     @Id 

     @GeneratedValue(strategy = IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="key", length=100)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }

    
    @Column(name="value", length=100)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


