package com.civil.detail;
// Generated Jan 20, 2020 10:27:03 PM by Hibernate Tools 4.3.1

/**
 * ProjectsItem generated by hbm2java
 */
public class ProjectsItemDetail extends BaseDetail {

    private Integer id;
    private ItemDetail itemDetail;
    private ProjectDetail projectDetail;
    private int quantity;
    private float totalPrice;
    private String itemList;

    private int projectId;
    private int itemId;

    private int calculationType;
    private String calculationSummary;

    public String getItemList() {
        return itemList;
    }

    public void setItemList(String itemList) {
        this.itemList = itemList;
    }

    public int getCalculationType() {
        return calculationType;
    }

    public void setCalculationType(int calculationType) {
        this.calculationType = calculationType;
    }

    public String getCalculationSummary() {
        return calculationSummary;
    }

    public void setCalculationSummary(String calculationSummary) {
        this.calculationSummary = calculationSummary;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ItemDetail getItemDetail() {
        return itemDetail;
    }

    public void setItemDetail(ItemDetail itemDetail) {
        this.itemDetail = itemDetail;
    }

    public ProjectDetail getProjectDetail() {
        return projectDetail;
    }

    public void setProjectDetail(ProjectDetail projectDetail) {
        this.projectDetail = projectDetail;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public float getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(float totalPrice) {
        this.totalPrice = totalPrice;
    }

    public int getProjectId() {
        return projectId;
    }

    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

}
