package com.civil.detail;
// Generated Jan 20, 2020 10:27:03 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;
import java.util.Date;

/**
 * Project generated by hbm2java
 */
public class ProjectDetail {

    private int id;
    private String projectName;

    @JsonFormat(pattern = "dd-MM-yyyy")
    private Date startDate;
    @JsonFormat(pattern = "dd-MM-yyyy")
    private Date endDate;
    private String startDate_st;
    private String endDate_st;
    private String ministry;
    private String description;
    private Integer createdBy;
    private Date creationDate;
    private Date modificationDate;
    private Integer status;
    private String note;

    public String getStartDate_st() {
        return startDate_st;
    }

    public void setStartDate_st(String startDate_st) {
        this.startDate_st = startDate_st;
    }

    public String getEndDate_st() {
        return endDate_st;
    }

    public void setEndDate_st(String endDate_st) {
        this.endDate_st = endDate_st;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public String getMinistry() {
        return ministry;
    }

    public void setMinistry(String ministry) {
        this.ministry = ministry;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getModificationDate() {
        return modificationDate;
    }

    public void setModificationDate(Date modificationDate) {
        this.modificationDate = modificationDate;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
